name: stardist_conda
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pyyaml
  - tensorflow-gpu  # explicitly request GPU version
  - stardist
  - git
  - pip
  - pip:
    - git+https://github.com/FrancisCrickInstitute/aiod_utils.git
