name: empanada_conda
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pyyaml
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu126
    - scikit-image
    - torch==2.11.0+cu126
    - torchvision==0.26.0+cu126
    - numba==0.59.0
    - numpy==1.26.4
    - empanada-dl==0.1.6
    - tqdm
    - git+https://github.com/FrancisCrickInstitute/aiod_utils.git