name: sam_conda
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.11
  - pytorch::pytorch==2.0.1
  - pytorch::torchvision==0.15.2
  - pytorch::torchaudio==2.0.2
  - pytorch::pytorch-cuda=11.8
  - mkl==2024.0
  - tqdm
  - pyyaml
  - pip
  - pip:
    - numpy>=1.24,<2
    - napari
    - scikit-image
    - git+https://github.com/FrancisCrickInstitute/segment-anything.git
    - opencv-python
    - git+https://github.com/FrancisCrickInstitute/aiod_utils.git