name: sam_conda
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch==2.0.1
  - pytorch::torchvision==0.15.2
  - pytorch::torchaudio==2.0.2
  - pytorch::pytorch-cuda=11.8
  - tqdm
  - pyyaml
  - pip
  - pip:
    - numpy
    - napari
    - scikit-image
    - git+https://github.com/facebookresearch/segment-anything.git
    - opencv-python