name: sam_conda
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - mkl==2024.0
  - tqdm
  - pyyaml
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu126
    - torch==2.11.0+cu126
    - torchvision==0.26.0+cu126
    - numpy>=1.24,<2
    - scikit-image
    - git+https://github.com/FrancisCrickInstitute/segment-anything.git
    - opencv-python
    - aiod_utils==0.1