name: sam_conda
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - mkl==2024.0
  - tqdm
  - pyyaml
  - pip
  - pip:
    - numpy>=1.24,<2
    - torch
    - scikit-image
    - git+https://github.com/FrancisCrickInstitute/segment-anything.git
    - opencv-python
    - git+https://github.com/FrancisCrickInstitute/aiod_utils.git