name: cellposesam_conda
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pyyaml
  - pip
  - pip:
    - numpy==1.26.4
    - cellpose>=4
    - git+ssh://git@github.com/FrancisCrickInstitute/aiod_utils.git