name: empanada_conda
channels:
  - pytorch
  - conda-forge
  - nvidia
  - nvidia/label/cuda-11.8.0
dependencies:
  - python=3.11
  - nvidia/label/cuda-11.8.0::cuda-toolkit
  - pytorch::pytorch==2.0.1
  - pytorch::torchvision==0.15.2
  - pytorch::torchaudio==2.0.2
  - pytorch::pytorch-cuda=11.8
  - pyyaml
  - pip
  - pip:
    - numpy==1.26.4
    - scikit-image
    - empanada-dl
    - git+https://github.com/FrancisCrickInstitute/aiod_utils.git