name: panseg_conda
channels:
  - conda-forge
  # `defaults` is optional, unless e.g. `conda-forge` has no cudnn 9.* when `defaults` has.
  # `defaults` of Anaconda is not accessible for many non-profit institutes such as EMBL.
  # - defaults
dependencies:
  - python=3.12
  - panseg
  - pip
  - pip:
      - git+https://github.com/FrancisCrickInstitute/aiod_utils.git
