name: unet_conda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - numba
  - scipy
  - matplotlib
  - scikit-image
  - beautifulsoup4
  - pyyaml
  - tqdm
  - imagecodecs
  - git
  - openssh
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu126
    - torch==2.11.0+cu126
    - torchvision==0.26.0+cu126
    - git+https://github.com/FrancisCrickInstitute/em-segment-pytorch.git
    - aiod_utils==0.1
