name: mitonet_conda
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch==2.0.1
  - pytorch::torchvision==0.15.2
  - pytorch::torchaudio==2.0.2
  - pytorch::pytorch-cuda=11.8
  - pyyaml
  - pip
  - pip:
    - numpy
    - scikit-image
    - empanada-dl
    - git+https://github.com/FrancisCrickInstitute/aiod_utils.git