name: empanada_conda
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pyyaml
  - git
  - pip
  - pip:
    - scikit-image
    - torch
    - numba==0.59.0
    - numpy==1.26.4
    - empanada-dl==0.1.6
    - tqdm
    - git+https://github.com/FrancisCrickInstitute/aiod_utils.git