name: empanada_conda
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pyyaml
  - pip
  - pip:
    - numpy==1.26.4
    - scikit-image
    - torch
    - empanada-dl
    - git+https://github.com/FrancisCrickInstitute/aiod_utils.git