name: mitonet_conda
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pyyaml
  - pip
  - pip:
    - numpy
    - scikit-image
    - torch
    - empanada-dl
    - git+https://github.com/FrancisCrickInstitute/aiod_utils.git