name: cellpose_conda
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pyyaml
  - pip
  - pip:
    - git+ssh://git@github.com/FrancisCrickInstitute/cellpose.git
    - git+ssh://git@github.com/FrancisCrickInstitute/aiod_utils.git