name: stardist_conda
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pyyaml
  - tensorflow  # Conda selects GPU/CPU build based on CUDA availability
  - stardist
  - git
  - pip
  - pip:
    - git+https://github.com/FrancisCrickInstitute/aiod_utils.git
