name: sam_conda
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - tqdm
  - pyyaml
  - pip
  - pip:
    - numpy
    - scikit-image
    - torch
    - torchvision
    - git+https://github.com/FrancisCrickInstitute/segment-anything.git
    - opencv-python
    - git+ssh://git@github.com/FrancisCrickInstitute/aiod_utils.git