
params {
    memory_per_job = 50.GB
}


process {
    executor = 'slurm'
    cache = 'lenient'
    debug = true
    ext.condaDir = "cuda"

    errorStrategy = { task.exitStatus in 135..143 ? 'retry' : 'terminate' }
    maxRetries = 3

    withLabel: gpu_process {
        queue = 'ga100'
        clusterOptions = '--gres=gpu:1'
        memory = { params.memory_per_job * task.attempt }
        time = { 15.min * task.attempt }
    }

    withName: '!run.*' {
        queue = 'ncpu'
        cpus = { 4 * task.attempt }
        time = { 10.min * Math.pow(2, task.attempt) }
    }
}

conda {
    conda.cacheDir = "/flask/conda/ddt/"
    conda.createTimeout = '1h'
    conda.useMamba = true
}