params {
    // Conservative default; set to available RAM on the local machine
    memory_per_job = 8.GB
}

process {
    executor = 'local'
    debug = true
    ext.condaDir = "generic"

    withLabel: gpu_process {
        cpus = 4
    }
}

conda {
    conda.cacheDir = "${params.root_dir}/conda/"
    conda.createTimeout = '1h'
}