name: sam_conda
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - tqdm
  - pyyaml
  - pip:
    - numpy
    - napari
    - scikit-image
    - torch
    - torchvision
    - git+https://github.com/facebookresearch/segment-anything.git