name: setup_model_conda
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - tqdm
    - requests
    # - git+https://github.com/FrancisCrickInstitute/AIoD-Model-Registry.git #TODO: return to remote registry !
    - -e /Users/ahmedn/aiod/AIoD-Model-Registry