name: combine_conda
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - numpy
    - pandas
    - scikit-image
    - dask
    - dask-image
    - psutil
    - numba
    - tqdm
    - git+ssh://git@github.com/FrancisCrickInstitute/aiod_utils.git